name: Run Selenium Tests

on:
  push:
    branches:
      - selenium_run
    paths:
      - 'src/main/java/App.java'

env:
  KEY: ${{ secrets.KEY }}      

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Download Chrome Stable Version
      run: |
        curl -o chrome-linux64.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chrome-linux64.zip
      shell: bash

    - name: Unzip Chrome
      run: |
        unzip chrome-linux64.zip -d chrome-linux64
        export CHROME_BIN=$(pwd)/chrome-linux64/chrome
        echo "export CHROME_BIN=$CHROME_BIN" >> $GITHUB_ENV
      shell: bash

    - name: Display Chrome Path
      run: |
        echo "Chrome binary path: $CHROME_BIN"
      shell: bash

    - name: Set up ChromeDriver
      run: |
        # WebDriverManager handles driver setup, so you can skip this step
      shell: bash

    - name: Set up Maven
      run: |
        if [ ! -e ~/.m2/repository ]; then
          start_time=$(date +%s)
          echo "Start Set up Maven: $(date)" >> execution_log.txt
          sudo apt-get install maven -y
          end_time=$(date +%s)
          execution_time=$((end_time - start_time))
          echo "End Set up Maven: $(date)" >> execution_log.txt
          echo "Execution time for Setup Maven: $execution_time seconds" >> execution_log.txt
        else
          echo "Maven is already installed (cached)."
        fi
      shell: bash

    - name: Build and run Selenium tests
      run: |
        start_time=$(date +%s)
        echo "Start Build and run Selenium tests: $(date)" >> execution_log.txt
        mvn test -DsuiteXmlFile=testng.xml
        end_time=$(date +%s)
        execution_time=$((end_time - start_time))
        echo "End Build and run Selenium tests: $(date)" >> execution_log.txt
        echo "Execution time for Build and run Selenium tests: $execution_time seconds" >> execution_log.txt
      env:
        CHROME_BIN: /usr/bin/google-chrome
        CHROMEDRIVER_PATH: /usr/local/bin/chromedriver

    - name: Upload Execution Log
      uses: actions/upload-artifact@v2
      with:
        name: execution-log
        path: execution_log.txt
