name: Run Selenium Tests

on:
  push:
    branches:
      - selenium_run

jobs:
  run_tests:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/vscode/devcontainers/java:0-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Maven
      run: mvn --version

    - name: Build and run Selenium tests
      run: mvn test -DsuiteXmlFile=testng.xml

    - name: Upload Execution Log
      uses: actions/upload-artifact@v2
      with:
        name: execution-log
        path: execution_log.txt
